name: Hello world workflow

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: hello world
        with:
          token: ${{ secrets.PAT_TOKEN }}
        run: echo "Hello world"
        shell: bash

      - name: Use Personal Access Token
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
            # Use the $PAT_TOKEN environment variable in your commands to interact with the GitHub API or perform other actions.
            echo "My Personal Access Token: $PAT_TOKEN"

  goodbye:
    runs-on: ubuntu-latest

    steps:
      - name: goodbye world
        with:
          token: ${{ secrets.PAT_TOKEN }}
        run: echo "Good bye world"
        shell: bash 

      - name: Use Personal Access Token
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Use the $PAT_TOKEN environment variable in your commands to interact with the GitHub API or perform other actions.
          echo "My Personal Access Token: $PAT_TOKEN"
