name: Create a comment on new issues

on:
    issues:
        types:
            [opened]

jobs:
    comment-with-action:
        runs-on:  ubuntu-latest
        steps:
            - name: 'Dump Github Context'
              run: echo '${{ toJSON(github.event) }}' | jq
              shell: bash
              # dash is used to indicate one block of a run.

            - name: Update PR with test results
              uses: edumserrano/find-create-or-update-comment@v1
              with:
                issue-number: ${{ github.event.issue.number }}
                body-includes: '<!-- pr-test-results -->'
                comment-author: 'github-actions[bot]'
                body: | # can be a single value or you can compose text with multi-line values
                  <!-- pr-test-results -->
                edit-mode: replace